apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  containers:
  - name: mysql
    image: mysql:8.0.35-debian
    stdin: true
    tty: true
    imagePullPolicy: IfNotPresent
    command: ["sh"]
#    volumeMounts:
#      - mountPath: "/mysqlbackup"
#        name: mysqlbackup
#  volumes:
#    - name: mysqlbackup
#      persistentVolumeClaim:
#        claimName: mysqlbackup
  tolerations:
    - key: "devops"
      operator: "Exists"
      effect: "NoSchedule"
  nodeSelector:
    devops: 'true'

