kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: eks-sc
#  annotations:
    # 設定為預設class
    #storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  fsType: ext4
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eks-pvc
  labels:
    app.kubernetes.io/instance: eks-pvc
    app.kubernetes.io/name: eks-pvc
spec:
  storageClassName: eks-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
kind: Pod
apiVersion: v1
metadata:
  name: alpine-1
spec:
  containers:
    - name: alpine
      image: alpine:3.12.0
      stdin: true
      tty: true
      volumeMounts:
      - mountPath: "/opt/files"
        name: external
  volumes:
    - name: external
      persistentVolumeClaim:
        claimName: eks-pvc
---
kind: Pod
apiVersion: v1
metadata:
  name: alpine-2
spec:
  containers:
    - name: alpine
      image: alpine:3.12.0
      stdin: true
      tty: true
      volumeMounts:
      - mountPath: "/opt/files"
        name: external
  volumes:
    - name: external
      persistentVolumeClaim:
        claimName: eks-pvc

