apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: example.com
spec:
  secretName: example.com
  issuerRef:
    name: letsencrypt-dns01
    kind: ClusterIssuer
  dnsNames:
    - 'example.com'
    - '*.example.com'
