version: '3.7'
services:
  nginx:
    image: nginx:1.17.8-alpine
    ports:
      - 80:80
    volumes:
      - './config/conf.d:/etc/nginx/conf.d'
      - './html:/usr/share/nginx/html'

networks:
  default:
    name: lib-nginx

