apiVersion: v1
kind: ConfigMap
metadata:
  name: php
data:
  default.conf: |
    server {
        listen       80;
        listen  [::]:80;
        server_name  localhost;
        location / {
          root /var/www/html;
          fastcgi_index  index.php;
          include fastcgi_params;
          fastcgi_param REQUEST_METHOD $request_method;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          fastcgi_pass 127.0.0.1:9000;
        }
    }
  index.php: |
    <?php echo 'hello world'; ?>
  server.php: |
    <?php echo '<pre>'; print_r($_SERVER); ?>
---
apiVersion: v1
kind: Pod
metadata:
  name: php
  labels:
    app.kubernetes.io/name: test-php
    app.kubernetes.io/instance: test-php
spec:
  containers:
  - name: nginx
    image: nginx:1.19.3-alpine
    ports:
      - name: http
        containerPort: 80
        protocol: TCP
    volumeMounts:
      - name: "php"
        mountPath: /etc/nginx/conf.d/default.conf
        subPath: default.conf
  - name: php
    image: php:7.4.11-fpm-alpine3.12
    volumeMounts:
      - name: "php"
        mountPath: /var/www/html/index.php
        subPath: index.php
  volumes:
  - name: "php"
    configMap:
      name: "php"
      items:
        - key: "default.conf"
          path: default.conf
        - key: "index.php"
          path: index.php
        - key: "server.php"
          path: server.php
---
apiVersion: v1
kind: Service
metadata:
  name: php
  labels:
    app.kubernetes.io/name: test-php
    app.kubernetes.io/instance: test-php
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: test-php
    app.kubernetes.io/instance: test-php
# ---
# apiVersion: networking.k8s.io/v1beta1
# kind: Ingress
# metadata:
#   name: php
#   labels:
#     app.kubernetes.io/name: test-php
#     app.kubernetes.io/instance: test-php
#   annotations:
#     kubernetes.io/ingress.class: nginx
# spec:
#   rules:
#     - host: "justin.hearts.tw"
#       http:
#         paths:
#           - path: /
#             backend:
#               serviceName: php
#               servicePort: 80

