---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: developer
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: developer
rules:
- apiGroups: ["*"]
  resources: ["namespaces","namespaces/status","pods/status","pods/log","events"]
  verbs: ["get","watch","list"]
- apiGroups: ["*"]
  resources: ["pods","deployment","replicaSet","configmaps","cluster","nodes","nodes/status"]
  verbs: ["get","watch","list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: developer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: developer
subjects:
- kind: ServiceAccount
  name: developer
  namespace: kube-system
