apiVersion: v1
kind: Secret
metadata:
  name: bot.jarvis-token
  namespace: kube-system
  annotations:
    kubernetes.io/service-account.name: bot.jarvis
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bot.jarvis
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bot.jarvis
  labels:
    from: solartninc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: bot.jarvis
  namespace: kube-system

