apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  containers:
  - name: myapp
    image: busybox:1.28
    command: ['sh', '-c', 'echo The app is running! && sleep 3600']
  initContainers:
  - name: initfirst
    image: busybox:1.28
    command: ['sh', '-c', "echo first init && sleep 10;"]
  - name: initsecond
    image: busybox:1.28
    command: ['exit 1']

