global:
  sendAnonymousUsage: false

ping:
  entryPoint: "ping"

api:
  dashboard: true
  insecure: true

entryPoints:
  ping:
    address: ":8082"
  web:
    address: :80
  websecure:
    address: :443

providers:
  file:
    filename: /etc/traefik/dynamic.yml
    watch: true

log:
  level: INFO
  filePath: /var/log/traefik/traefik.log
  format: common
  maxSize: 10
  maxBackups: 3
  maxAge: 7
  compress: true

accesslog:
  addInternals: false
  filePath: /var/log/traefik/access.log
  format: common # json

certificatesResolvers:
  letsesolver:
    acme:
      preferredChain: 'ISRG Root X1'
      keyType: 'RSA4096'
      httpChallenge:
        entryPoint: web
      email: "ting911111@gmail.com"
      storage: /letsencrypt/acme.json
      #caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      caServer: https://acme-v02.api.letsencrypt.org/directory
